/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package campominado;

import java.awt.Toolkit;

/**
 *
 * @author rodri
 */
public class GameOver extends javax.swing.JFrame {
 TelaJogo teladojogo = new TelaJogo();
    /**
     * Creates new form GameOver
     */
    public GameOver() {
        initComponents();
        setIcon();
    }
     public void ExportarPontos (TelaJogo pontos){
        lbl_Pontos.setText(pontos.getName());
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_Pontos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Campo Minado");
        setMinimumSize(new java.awt.Dimension(364, 270));
        setPreferredSize(new java.awt.Dimension(364, 270));
        getContentPane().setLayout(null);

        jButton1.setText("Novo Jogo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 180, 90, 23);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Pontos:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 140, 80, 20);

        lbl_Pontos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_Pontos.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lbl_Pontos);
        lbl_Pontos.setBounds(180, 140, 50, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/game Over.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(367, 240));
        jLabel1.setMinimumSize(new java.awt.Dimension(367, 240));
        jLabel1.setPreferredSize(new java.awt.Dimension(367, 260));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 360, 230);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Menu novojogo = new Menu();
    novojogo.setVisible(true);
    dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_Pontos;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagens/logo.png")));
    }
}
