/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package campominado;

import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Toolkit;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author rodri
 */
public class Menu extends javax.swing.JFrame {
          
   
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents(); 
        setIcon();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Jogar = new javax.swing.JButton();
        btn_Sair = new javax.swing.JButton();
        btn_Regras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Campo Minado\n\n");
        setAutoRequestFocus(false);
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        btn_Jogar.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        btn_Jogar.setText("New Game");
        btn_Jogar.setBorder(null);
        btn_Jogar.setBorderPainted(false);
        btn_Jogar.setContentAreaFilled(false);
        btn_Jogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_JogarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Jogar);
        btn_Jogar.setBounds(190, 180, 120, 30);

        btn_Sair.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        btn_Sair.setText("Sair");
        btn_Sair.setContentAreaFilled(false);
        btn_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SairActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Sair);
        btn_Sair.setBounds(210, 270, 80, 31);

        btn_Regras.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        btn_Regras.setText("Regras ");
        btn_Regras.setContentAreaFilled(false);
        btn_Regras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegrasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Regras);
        btn_Regras.setBounds(200, 230, 110, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FundoInicio.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 405));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 405));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -30, 500, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_JogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_JogarActionPerformed
        TelaJogo telaJogo = new TelaJogo();
        telaJogo.setVisible(true);

        this.dispose();
        
         
        
    }//GEN-LAST:event_btn_JogarActionPerformed

    private void btn_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SairActionPerformed
                 
        System.exit(0);
    }//GEN-LAST:event_btn_SairActionPerformed

    private void btn_RegrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegrasActionPerformed
           
        Regras telaJogo = new Regras();
        telaJogo.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_RegrasActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
     
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Jogar;
    private javax.swing.JButton btn_Regras;
    private javax.swing.JButton btn_Sair;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
           setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagens/logo.png")));
        }
}
